sudo: false
install: true
language:
  - erlang
env:
  global:
    - TRAVIS_CI=true
before_install:
  - sudo apt-get install -qq sendmail
  - ./rebar3 dialyzer
script:
  - make
  - make ct
notifications:
  email:
    - shuieryin@gmail.com
otp_release:
  - 18.2