sudo: false
install: true
language:
  - erlang

env:
  global:
    - TRAVIS_CI=false

addons:
  apt:
    packages:
      - lynx

#before_install:
#  - ./rebar3 dialyzer

script:
  - make
  - make ct_analyze

notifications:
  email:
    - shuieryin@gmail.com

otp_release:
  - 18.2