sudo: false
install: true
language:
  - erlang

env:
  global:
    - TRAVIS_CI=true

#addons:
#  apt:
#    packages:
#      - sendmail

before_install:
  - ./rebar3 dialyzer

script:
  - make
  - make ct

notifications:
  email:
    - shuieryin@gmail.com

otp_release:
  - 18.2