sudo: false
install: true
language:
  - erlang

env:
  global:
    - TRAVIS_CI=true
    
services:
  - redis-server

#addons:
#  apt:
#    packages:
#      - lynx

#before_install:
#  - ./rebar3 dialyzer

script:
  - make
  - make ct_analyze

notifications:
  email:
    - shuieryin@gmail.com

otp_release:
  - 18.3
