sudo: false
install: true
language:
  - erlang

env:
  global:
    - TRAVIS_CI=true

services:
  - redis-server

script:
  - make

notifications:
  email:
    - shuieryin@gmail.com

otp_release:
  - 19.3