sudo: false
install: true
language:
  - erlang

env:
  global:
    - TRAVIS_CI=true

services:
  - redis-server

#skip automated regression tests
script:
  - make install_rebar3
  - make build
  - make ck

notifications:
  email:
    - shuieryin@gmail.com

otp_release:
  - 19.3