sudo: false
install: true
language:
  - erlang

env:
  global:
    - TRAVIS_CI=false

#addons:
#  apt:
#    packages:
#      - sendmail

#before_install:
#  - ./rebar3 dialyzer

script:
  - make

notifications:
  email:
    - shuieryin@gmail.com

otp_release:
  - 18.2